function [ R_t_scaled, implied_mean, implied_std, corr ] ...
    = compute_rates( nsep, hp, real, ...
    range, FFR_nom_t_scaled, FFR_real_t_scaled, ...
    c_t, c_tm1, l_t, ...
    Et_c_tp1, Et_c_tp2, Et_pi_tp1, Et_l_tp1, Et_l_tp2, Vt_c_tp1, ...
    Vt_c_tp2, Vt_pi_tp1, Vt_l_tp1, Ct_c_pi_tp1, Ct_c_l_tp1, ...
    Ct_pi_l_tp1, Ct_c_l_tp2, Ct_c_tp1_tp2, Ct_c_tp1_l_tp2, ...
    Ct_pi_tp1_c_tp2, Ct_pi_tp1_l_tp2 )

[ beta, alpha, nu, phi, ymax, ymin ] = get_params( nsep, hp, real );

if real == 0
    chi_1t = (nu*(1-alpha) - 1)*Et_c_tp1 - phi*nu*(1-alpha)*c_t ...
        + (1-nu)*(1-alpha)*Et_l_tp1 - Et_pi_tp1 ...
        + 1/2*(nu*(1-alpha) - 1)^2*Vt_c_tp1 ...
        + 1/2*((1-nu)*(1-alpha))^2*Vt_l_tp1 + 1/2*Vt_pi_tp1 ...
        - (1-nu)*(1-alpha)*Ct_pi_l_tp1 ...
        + (nu*(1-alpha) - 1)*(1-nu)*(1-alpha)*Ct_c_l_tp1 ...
        - (nu*(1-alpha) - 1)*Ct_c_pi_tp1;
    
    chi_2t = nu*(1-alpha)*Et_c_tp2 - (phi*nu*(1-alpha) + 1)*Et_c_tp1 ...
        + (1-nu)*(1-alpha)*Et_l_tp2 - Et_pi_tp1 ...
        + 1/2*(nu*(1-alpha))^2*Vt_c_tp2 ...
        + 1/2*(phi*nu*(1-alpha) + 1)^2*Vt_c_tp1 ...
        + 1/2*((1-nu)*(1-alpha))^2*Vt_l_tp1 + 1/2*Vt_pi_tp1 ...
        - nu*(1-alpha)*Ct_pi_tp1_c_tp2 ...
        + (phi*nu*(1-alpha) + 1)*Ct_c_pi_tp1 ...
        - (1-nu)*(1-alpha)*Ct_pi_tp1_l_tp2 ...
        - nu*(1-alpha)*(phi*nu*(1-alpha) + 1)*Ct_c_tp1_tp2 ...
        + nu*(1-nu)*(1-alpha)^2*Ct_c_l_tp2 ...
        - (phi*nu*(1-alpha) + 1)*(1-nu)*(1-alpha)*Ct_c_tp1_l_tp2;
    
    chi_3t = (nu*(1-alpha) - 1)*c_t - phi*nu*(1-alpha)*c_tm1 ...
        + (1-nu)*(1-alpha)*l_t;
    
    chi_4t = nu*(1-alpha)*Et_c_tp1 - (phi*nu*(1-alpha) + 1)*c_t ...
        + (1-nu)*(1-alpha)*Et_l_tp1 + 1/2*(nu*(1-alpha))^2*Vt_c_tp1 ...
        + 1/2*((1-nu)*(1-alpha))^2*Vt_l_tp1 ...
        + nu*(1-nu)*(1-alpha)^2*Ct_c_l_tp1;
    
    FFR_t_scaled = FFR_nom_t_scaled;
    chart_title = 'Annualized Nominal Interest Rate';
else
    chi_1t = (nu*(1-alpha) - 1)*Et_c_tp1 - phi*nu*(1-alpha)*c_t ...
        + (1-nu)*(1-alpha)*Et_l_tp1 + 1/2*(nu*(1-alpha) - 1)^2*Vt_c_tp1 ...
        + 1/2*((1-nu)*(1-alpha))^2*Vt_l_tp1 ...
        + (nu*(1-alpha) - 1)*(1-nu)*(1-alpha)*Ct_c_l_tp1;
    
    chi_2t = nu*(1-alpha)*Et_c_tp2 - (phi*nu*(1-alpha) + 1)*Et_c_tp1 ...
        + (1-nu)*(1-alpha)*Et_l_tp2 + 1/2*(nu*(1-alpha))^2*Vt_c_tp2 ...
        + 1/2*(phi*nu*(1-alpha) + 1)^2*Vt_c_tp1 ...
        + 1/2*((1-nu)*(1-alpha))^2*Vt_l_tp1 ...
        - nu*(1-alpha)*(phi*nu*(1-alpha) + 1)*Ct_c_tp1_tp2 ...
        + nu*(1-nu)*(1-alpha)^2*Ct_c_l_tp2 ...
        - (phi*nu*(1-alpha) + 1)*(1-nu)*(1-alpha)*Ct_c_tp1_l_tp2;
    
    chi_3t = (nu*(1-alpha) - 1)*c_t - phi*nu*(1-alpha)*c_tm1 ...
        + (1-nu)*(1-alpha)*l_t;
    
    chi_4t = nu*(1-alpha)*Et_c_tp1 - (phi*nu*(1-alpha) + 1)*c_t ...
        + (1-nu)*(1-alpha)*Et_l_tp1 + 1/2*(nu*(1-alpha))^2*Vt_c_tp1 ...
        + 1/2*((1-nu)*(1-alpha))^2*Vt_l_tp1 ...
        + nu*(1-nu)*(1-alpha)^2*Ct_c_l_tp1;
    
    FFR_t_scaled = FFR_real_t_scaled;
    chart_title = 'Annualized Real Interest Rate';
end

R_t_inv = beta * (exp(chi_1t) - beta*phi*exp(chi_2t)) ./ (exp(chi_3t) - beta*phi*exp(chi_4t));
R_t = 1 ./ R_t_inv; % quarterly gross rate
R_t_ann = R_t .^ 4; % annualized gross nominal rate
R_t_scaled = log(R_t_ann) .* 100;

plot(date(range), R_t_scaled(range), date(range), FFR_t_scaled);
title(chart_title);
legend('Implied', 'FFR');
xlim([datenum(1960, 1, 1) datenum(2006, 10, 1)]);
ylim([ymin ymax])
%file = strcat('figs/crra-real_', int2str(i), '.png');
%print(file, '-dpng');

implied_mean = mean(R_t_scaled(range));
implied_std = std(R_t_scaled(range));
corr = corrcoef(R_t_scaled(range), FFR_t_scaled(range));

end

